# Generated by Django 6.0.5 on 2026-05-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engins', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.IntegerField(default=1)),
                ('nb_jours', models.IntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engins.engin')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='locations.location')),
            ],
        ),
    ]
