# Generated by Django 6.0.5 on 2026-05-15 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement')], max_length=30)),
                ('reference_transaction', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='locations.location')),
            ],
        ),
    ]
