# Generated by Django 6.0.5 on 2026-05-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='engins.engin')),
            ],
        ),
    ]
